### ISSUE TITLE
mkinitcpio-archiso and reflector could NOT found

### ISSUE THREAD

**Issue by yanboyang713** [gsanhueza/ArchISOMaker#10]
Hello,

when I run sudo ./build.sh -v. give me the error below

```
error: target not found: mkinitcpio-archiso
error: target not found: reflector
==> ERROR: Failed to install packages to new root
```

**Comment by gsanhueza** [comment]
Archiso (as a package) is a dependency.
Make sure you have it in your system (you can install it with `sudo pacman -S archiso`).
The same goes for reflector (`sudo pacman -S reflector`).

The simplest way to compile an ArchLinux ISO with my script is by using ArchLinux in the first place (because the idea of the repository is to generate an ISO with packages inside, so you don't need internet to install the operating system "again").

If you have doubts, feel free to comment them (and if you're using another distro to try these scripts, let me know so I can test them).

**Comment by yanboyang713** [comment]
Hello @gsanhueza,

Thanks for your help.

I found the root cause of this issue. My internet connection is not stable.

Very good project; I will use your [ArchISOMaker](https://github.com/gsanhueza/ArchISOMaker) make my own ISO
