### ISSUE TITLE
systemd does not booted

### ISSUE THREAD

**Issue by yanboyang713** [gsanhueza/ArchISOMaker#13]
Hello @gsanhueza 

Good day to you,

Currently, I want to using **timedatectl** get the current time zone as default.
However, I got the error msg **"system has not been booted with systemd as init system"**.
Do you know how to booted with systemd?

Script below:
```
set_zoneinfo()
{
    print_message ">>> Linking zoneinfo <<<"
    # Get the current time zone
    default_timezone=$(timedatectl show --property=Timezone --value)
    # Display the time zone
    echo "Default Time Zone: $default_timezone. Check /usr/share/zoneinfo/ for more options"

    read -r -p "Enter your Time Zone (press enter for default: $default_timezone): " timezone < /dev/tty
    # Set default value if name is empty
    timezone=${timezone:-$default_timezone}

    ln -s /usr/share/zoneinfo/$timezone /etc/localtime -f
}
```

Thanks,
Boyang Y

**Comment by gsanhueza** [comment]
Hello @yanboyang713 

This issue fits better in [my ArchScripts repo](https://github.com/gsanhueza/ArchScripts/issues).
Still, I can answer it here, as it's more visible.

I can deduce you're adapting the [config](https://github.com/gsanhueza/ArchScripts/blob/master/config.sh) file.
But if you check the [arch_install](https://github.com/gsanhueza/ArchScripts/blob/master/arch_install.sh) file, it runs `config.sh` (as `./$CONFFILE`) in the `configure_system` function, where it uses `arch-chroot` to enter the new system and configure it.

I'd recommend creating a new method in `arch_install.sh` instead, so you can use systemd, because a chroot'ed system has not been "initialized" (which explains the *not booted* error.)

**Comment by yanboyang713** [comment]
Hello @gsanhueza 

Thank you so much.

ok, understand now

Thanks
Boyang Y
