### ISSUE TITLE
guided gui ? 

### ISSUE THREAD

**Issue by XxnittanixX** [gsanhueza/ArchISOMaker#8]
im serious and i know its alot but guided gui and tips

**Comment by gsanhueza** [comment]
The purpose behind my implementation of an Arch installer is to install it `non-interactively`.
The idea is interesting, but there are already available GUI installers in other projects.

**Comment by D3vil0p3r** [comment]
Just a question @gsanhueza If you install a Desktop Environment and a Login Manager, or if you implement a "liveuser" account that you use for logging in the LIVE Environment, is it true that the zsh scripts inside airootfs/root don't run anymore?

For example, I'm thinking about the .zshrc file. If you login directly on GNOME, since you are not in tty, that script is not run... I think. So maybe for running them we are forced to stay in tty (I guess custom_airootfs.sh could work also in a GUI environment, but it is deprecated)

**Comment by gsanhueza** [comment]
@D3vil0per If you want to install a desktop environment while running the Live ISO (I already offer i3 in it, and you can test it by running `startx` from the TTY when booting the generated ISO), the scripts will still be in `/root`.
Additionally, the `.zshrc` file will still greet you when opening a new terminal (Meta + Enter when running i3).

If you still want to install a desktop environment with a new user in the live environment (instead of your disk drive), then yeah, the liveuser account will not have the scripts, but they can be found in `/root` (instead of `/home/liveuser`).

You're not forced to stay in TTY to access the scripts. 
I installed i3 in the live ISO to be able to use GUI apps, such as `gparted`, and it's still possible to access the installation scripts.
